### ISSUE TITLE
Confusión de posición de meses y días en el dataset.

### ISSUE THREAD

**Issue by MatiasLoiseau** [thedarsideofit/covid19-ar#1]
Hola Diego cómo va? Primero que todo quiero agradecerte porque estoy estudiando el camino de datascience y tu código me sirvió mucho para el manejo de datos. Si visitas mi código hice un copy-paste fuerte.

Quería comentarte que a partir de el 5 de abril te estuviste confundiendo al momento de cargar los datos, porque estas poniendo los días en el lugar de los meses. 

Espero haberte ayudado con esta pavada pero nuevamente aprovecho la ocasión para decirte muchas gracias.

**Comment by thedarsideofit** [comment]
Gracias a vos por la corrección!
